services:
  app:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=rememberHun
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - rememberhun-network

volumes:
  postgres-dev-data:


